// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"collabotask/internal/config"
	"collabotask/internal/infrastructure/database"
	"collabotask/internal/server"
	"collabotask/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger(config)
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(db)
	authUseCase := ProvideAuthUseCase(userRepository, config)
	authHandler := ProvideAuthHandler(authUseCase)
	userHandler := ProvideUserHandler(authUseCase)
	workspaceRepository := ProvideWorkspaceRepository(db)
	workspaceMemberRepository := ProvideWorkspaceMemberRepository(db)
	workspaceUseCase := ProvideWorkspaceUseCase(workspaceRepository, workspaceMemberRepository, userRepository)
	workspaceHandler := ProvideWorkspaceHandler(workspaceUseCase)
	engine := ProvideRouter(config, logger, authHandler, userHandler, workspaceHandler)
	server := ProvideServer(config, engine)
	v := ProvideCleanup(db)
	app := &App{
		Server:  server,
		DB:      db,
		Config:  config,
		Logger:  logger,
		Cleanup: v,
	}
	return app, nil
}

// wire.go:

type App struct {
	Server  *server.Server
	DB      *database.DB
	Config  *config.Config
	Logger  *logger.Logger
	Cleanup func()
}

var (
	ConfigSet     = wire.NewSet(ProvideConfig)
	LoggerSet     = wire.NewSet(ProvideLogger)
	DBSet         = wire.NewSet(ProvideDB, ProvideCleanup)
	RepositorySet = wire.NewSet(
		ProvideUserRepository,
		ProvideWorkspaceRepository,
		ProvideWorkspaceMemberRepository,
	)
	UseCaseSet = wire.NewSet(
		ProvideAuthUseCase,
		ProvideWorkspaceUseCase,
	)
	HandlerSet = wire.NewSet(
		ProvideAuthHandler,
		ProvideUserHandler,
		ProvideWorkspaceHandler,
	)
	RouterSet = wire.NewSet(ProvideRouter)
	ServerSet = wire.NewSet(ProvideServer)
)
